### ISSUE TITLE
Security Issue: Mixed Content warnings

### ISSUE THREAD

**Issue by a3rosol** [themeblvd/theme-blvd-shortcodes#8]
Hi there.

I'm using this plugin together with alyeska and found, that static content (images mostly) in the WP Admin Posting area is served via http and not https. Could you introduce protocol relative urls?

**Comment by themeblvd** [comment]
Hi,

Can you try and be more specific? Where is the shortcodes plugin serving static image URL's?

**Comment by a3rosol** [comment]
Mixed Content: The page at 'https://xxx/wp-admin/post.php?post=1239&action=edit' was loaded over HTTPS, but requested an insecure image 'http://xxx/wp-content/themes/alyeska/framework/assets/images/shortcodes/icons/star_half.png'. This content should also be served over HTTPS.

It seems to have this problem with all the icons.
